#ifndef SAMPLEWINDOWGLOBAL_H
#define SAMPLEWINDOWGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GANDIS_SAMPLE_WINDOW_LIBRARY)
#  define GANDIS_SAMPLE_WINDOW_EXPORT Q_DECL_EXPORT
#else
#  define GANDIS_SAMPLE_WINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // SAMPLEWINDOWGLOBAL_H
